[package]
name = "ocg-infra"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Infrastructure implementations for OCG Manager"

[dependencies]
anyhow = "1"
base64 = "0.22"
uuid = { version = "1", features = ["v4"] }
